# Generated by Django 4.2.16 on 2026-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID client')),
                ('livreur_id', models.IntegerField(blank=True, null=True, verbose_name='ID livreur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY', 'Prête pour livraison'), ('PICKED_UP', 'Récupérée par le livreur'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('delivery_city', models.CharField(default='Conakry', max_length=100)),
                ('notes', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('items_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande livraison',
                'verbose_name_plural': 'Commandes livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🍽️', max_length=10)),
            ],
            options={
                'verbose_name': 'Catégorie de plats',
                'verbose_name_plural': 'Catégories de plats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(verbose_name='ID du propriétaire (auth service)')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(default='Conakry', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurants/banners/')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert')),
                ('delivery_time_min', models.IntegerField(default=20, help_text='Temps de livraison minimum (min)')),
                ('delivery_time_max', models.IntegerField(default=45, help_text='Temps de livraison maximum (min)')),
                ('min_order', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Commande minimum (GNF)')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=5000, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (GNF)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Populaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.foodcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='delivery.restaurant')),
            ],
            options={
                'verbose_name': 'Plat / Article menu',
                'verbose_name_plural': 'Plats / Articles menu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('restaurant_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('livreur_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.deliveryorder')),
            ],
            options={
                'verbose_name': 'Notation livraison',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='delivery.deliveryorder')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.restaurant'),
        ),
    ]
