# Generated by Django 4.2.16 on 2026-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY', 'Prête pour livraison'), ('PICKED_UP', 'Prise en charge par le livreur'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée'), ('LIVREUR_CANCELLED', 'Annulée par le livreur (confirmation requise)')], default='PENDING', max_length=20),
        ),
    ]
