# Generated by Django 6.0.7 on 2026-07-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Réduction (GNF)'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=30, verbose_name='Code promo utilisé'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_city',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100),
        ),
        migrations.CreateModel(
            name='DeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('CASH_ON_DELIVERY', 'Paiement à la livraison')], default='CASH_ON_DELIVERY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=64)),
                ('otp_code', models.CharField(blank=True, max_length=10, verbose_name='Code de confirmation (simulation)')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='delivery.deliveryorder')),
            ],
            options={
                'verbose_name': 'Paiement livraison',
            },
        ),
    ]
