# Generated by Django 4.2.16 on 2026-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🛍️', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('livreur_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée par la boutique'), ('PROCESSING', 'En préparation'), ('READY', 'Prête'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('PICKUP_READY', 'Prête pour retrait'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Livraison'), ('PICKUP', 'Retrait en boutique')], default='DELIVERY', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(default='Conakry', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('items_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande marketplace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(verbose_name='ID propriétaire')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Conakry', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Propose la livraison')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='marketplace.category')),
            ],
            options={
                'verbose_name': 'Boutique',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (GNF)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('condition', models.CharField(choices=[('NEW', 'Neuf'), ('USED_GOOD', 'Occasion - Bon état'), ('USED_FAIR', 'Occasion - État correct')], default='NEW', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('has_delivery', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.shop')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='marketplace.marketplaceorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.shop'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
            ],
            options={
                'verbose_name': 'Avis produit',
                'unique_together': {('product', 'client_id')},
            },
        ),
    ]
