# Generated by Django 4.2.16 on 2026-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée par la boutique'), ('PROCESSING', 'En préparation'), ('READY', 'Prête'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('PICKUP_READY', 'Prête pour retrait'), ('CANCELLED', 'Annulée'), ('LIVREUR_CANCELLED', 'Annulée par le livreur (confirmation requise)')], default='PENDING', max_length=20),
        ),
    ]
