# Generated by Django 4.2.16 on 2026-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID client')),
                ('coursier_id', models.IntegerField(blank=True, null=True, verbose_name='ID coursier')),
                ('livreur_id', models.IntegerField(blank=True, null=True, verbose_name='ID livreur')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte - En attente de coursier'), ('ASSIGNED', 'Coursier assigné'), ('SHOPPING', "En cours - Courses en train d'être faites"), ('NEED_DELIVERY', 'Prête - Cherche livreur'), ('DELIVERING', 'En livraison'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20)),
                ('title', models.CharField(default='Mes courses', max_length=200, verbose_name='Titre')),
                ('market_name', models.CharField(default='Marché Madina', max_length=200, verbose_name='Marché cible')),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('delivery_city', models.CharField(default='Conakry', max_length=100)),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Budget courses (GNF)')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('is_delivery_needed', models.BooleanField(default=True, verbose_name='Livraison nécessaire')),
                ('service_fee', models.DecimalField(decimal_places=0, default=10000, max_digits=12, verbose_name='Frais de service (GNF)')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Frais de livraison (GNF)')),
                ('actual_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total réel dépensé (GNF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de courses',
                'verbose_name_plural': 'Demandes de courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('coursier_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('livreur_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='market.marketrequest')),
            ],
            options={
                'verbose_name': 'Notation courses',
            },
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Article')),
                ('quantity', models.CharField(help_text='Ex: 2 kg, 3 pièces, 1 botte', max_length=100, verbose_name='Quantité')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix estimé (GNF)')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix réel (GNF)')),
                ('is_found', models.BooleanField(default=False, verbose_name='Trouvé au marché')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name="Notes sur l'article")),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.marketrequest')),
            ],
            options={
                'verbose_name': 'Article de courses',
                'verbose_name_plural': 'Articles de courses',
            },
        ),
        migrations.CreateModel(
            name='CoursierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursier_id', models.IntegerField(verbose_name='ID coursier')),
                ('message', models.TextField(blank=True, verbose_name='Message du coursier')),
                ('proposed_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Frais de service proposés (GNF)')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.marketrequest')),
            ],
            options={
                'verbose_name': 'Offre coursier',
                'unique_together': {('request', 'coursier_id')},
            },
        ),
    ]
