# Generated by Django 6.0.7 on 2026-07-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Réduction sur les frais de service (GNF)'),
        ),
        migrations.AddField(
            model_name='marketrequest',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=30, verbose_name='Code promo utilisé'),
        ),
        migrations.AlterField(
            model_name='marketrequest',
            name='delivery_city',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100),
        ),
    ]
