# Generated by Django 4.2.16 on 2026-03-07 16:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client'), ('LIVREUR', 'Livreur'), ('RESTAURANT', 'Restaurant / Vendeur alimentaire'), ('BOUTIQUIERR', 'Boutiquierr (Marché Numérique)'), ('COURSIER', 'Coursier de Marché')], default='CLIENT', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('city', models.CharField(default='Conakry', max_length=100, verbose_name='Ville')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('is_available', models.BooleanField(default=True, help_text='Pour les livreurs et coursiers : indique la disponibilité', verbose_name='Disponible')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie / Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Moto'), ('VELO', 'Vélo'), ('VOITURE', 'Voiture'), ('PIED', 'À pied')], default='MOTO', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de permis')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='livreurs/ids/', verbose_name="Pièce d'identité")),
                ('total_deliveries', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('zone', models.CharField(default='Conakry', max_length=100, verbose_name='Zone de livraison')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Livreur',
            },
        ),
        migrations.CreateModel(
            name='CoursierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_markets', models.CharField(blank=True, help_text='Ex: Madina, Cosa, Dixinn...', max_length=500, verbose_name='Marchés préférés')),
                ('total_missions', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('zone', models.CharField(default='Conakry', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coursier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Coursier',
            },
        ),
    ]
