# Generated by Django 6.0.7 on 2026-07-23 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage'), ('FIXED', 'Montant fixe')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Valeur (% ou GNF)')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant minimum de commande (GNF)')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Vide = illimité', null=True, verbose_name="Limite d'utilisation")),
                ('times_used', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, help_text="Vide = pas d'expiration", null=True, verbose_name="Date d'expiration")),
                ('applicable_order_types', models.JSONField(default=list, help_text='Sous-ensemble de DELIVERY, MARKET, MARKETPLACE. Vide = tous.', verbose_name='Types de commande concernés')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='coursierprofile',
            name='zone',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100),
        ),
        migrations.AlterField(
            model_name='livreurprofile',
            name='zone',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100, verbose_name='Zone de livraison'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100, verbose_name='Ville'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Maison, Bureau...', max_length=50, verbose_name='Libellé')),
                ('full_address', models.TextField(verbose_name='Adresse complète')),
                ('city', models.CharField(choices=[('Conakry', 'Conakry'), ('Kindia', 'Kindia'), ('Kankan', 'Kankan'), ('Labé', 'Labé'), ("N'Zérékoré", "N'Zérékoré"), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Faranah', 'Faranah'), ('Kissidougou', 'Kissidougou'), ('Guéckédou', 'Guéckédou')], default='Conakry', max_length=100, verbose_name='Ville')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Livraison'), ('MARKET', 'Mon Marché'), ('MARKETPLACE', 'Boutiques')], max_length=20)),
                ('order_id', models.IntegerField(verbose_name='ID de la commande (service concerné)')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='authentication.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation de code promo',
                'verbose_name_plural': 'Utilisations de codes promo',
                'ordering': ['-redeemed_at'],
                'unique_together': {('promo_code', 'user', 'order_type', 'order_id')},
            },
        ),
    ]
