# Generated by Django 6.0.7 on 2026-07-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_address_latitude_address_longitude_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('EMAIL_CHANGE', 'Changement email')], max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('target_email', models.EmailField(blank=True, max_length=254, verbose_name='Nouvelle adresse (en attente)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'ordering': ['-created_at'],
            },
        ),
    ]
